
#user  nobody;
# you must set worker processes based on your CPU cores, nginx does not benefit from setting more than that
# some last versions calculate it automatically
worker_processes  auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
error_log  logs/error.log  info;

#pid        logs/nginx.pid;

# number of file descriptors used for nginx
# the limit for the maximum FDs on the server is usually set by the OS.
# if you don't set FD's then OS settings will be used which is by default 2000
# worker_rlimit_nofile 100000 ;  # already setted ?

# for centos7
# vi /etc/security/limits.conf
# *    soft    nofile 100001
# *    hard    nofile 100002

events {
    # determines how much clients will be served per worker
    # max clients = worker_connections * worker_processes
    # max clients is also limited by the number of socket connections available on the system (~64k)
    worker_connections  32768 ;
}

# for performance turning: https://gist.github.com/denji/8359866

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    # performance
    # to boost I/O on HDD we can disable access logs
    # access_log off;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    # 避免nginx 因为 浏览器版本太低 而 主动关闭连接，导致TIME_OUT问题
    keepalive_disable none;

    
    # 这个将为打开文件指定缓存，默认是没有启用的，max 指定缓存数量，
    # 建议和打开文件数一致，inactive 是指经过多长时间文件没被请求后删除缓存。
    open_file_cache max=10240 inactive=20s;
    # open_file_cache 指令中的inactive 参数时间内文件的最少使用次数，
    # 如果超过这个数字，文件描述符一直是在缓存中打开的，如上例，如果有一个
    # 文件在inactive 时间内一次没被使用，它将被移除。
    open_file_cache_min_uses 1;
    # 这个是指多长时间检查一次缓存的有效信息
    open_file_cache_valid 30s;

    #gzip  on;

    ## lua start 
    # 设置默认 lua 搜索路径，添加 lua 路径
    # 此处写相对路径时，对启动 nginx 的路径有要求，必须在 nginx 目录下启动，require 找不到
    # comm.param 绝对路径当然也没问题，但是不可移植，因此应使用变量 $prefix 或
    # ${prefix}，OR 会替换为 nginx 的 prefix path。
    lua_package_path '$prefix/lua/?.lua;/blah/?.lua;;';

    # 这里设置为 off，是为了避免每次修改之后都要重新 reload 的麻烦。
    # 在生产环境上务必确保 lua_code_cache 设置成 on。
    lua_code_cache off;

    # shared_dict 在 Nginx 所有 worker 之间共享
    # LRU 算法 来判断缓存是否在内存占满时被清除。
    # 用的是共享内存，每次操作都是全局锁，
    # 如果高并发环境，不同 worker 之间容易引起竞争。
    # 所以单个 shared.dict 的体积不能过大。
    lua_shared_dict global_shared_dict 16m;
    lua_shared_dict my_locks 10m;

    lua_shared_dict mcard_dict 300m;

    lua_shared_dict my_limit_req_store 200m;


    # nginx主进程加载nginx配置文件的时候在lua虚拟机全局范围内调用 ?
    init_by_lua_file  lua/_init.lua ;
    
    # 在nginx工作进程启动时调用的。 
    # init_worker_by_lua_file  lua/_init.lua ;
    
    ## lua end

    include /etc/nginx/conf.d/*.conf;
}
