# vi ./config/alacritty/alacritty.toml

# https://alacritty.org/config-alacritty.html#s12
# config change will affect UI right now
[font]
# normal.family="DejaVu Sans Mono"
normal.family="Source Code Pro"
size=10  # won't affect by xrandr --dpi setting

[window]
opacity=0.9


[cursor]
style.blinking="Always"
# blink_interval=750
blink_timeout=0

