#!bash

myytdl() {
    if [ "$#" -lt 1 ]; then
        echo 'usage: myytdl url [sub-language] '
        echo e.g. 'myytdl  https://xxxx en'
    else
        # if $2 is not empty, then set sub-lang to $2
        sub_lang=""
        if [ -n "$2" ]; then
            sub_lang="--sub-lang=$2"
        fi

        yt-dlp --ignore-errors --rm-cache-dir -c --write-auto-sub  \
            -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'  \
            -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' --cookies-from-browser chrome $1

    fi
}

mov2mp4() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <dir or .mov>"
        return
    fi
    
    if [ -d "$1" ]; then
        # list all .mov (ignore case)  files in the directory
        for file in $(find "$1" -type f -iname "*.mov"); do
            # convert .mov to .mp4
            ffmpeg -i "$file" -c:v libx264  -c:a aac -movflags +faststart "${file%.*}.mp4"
        done
    elif [ -f "$1" ]; then
        # convert .mov to .mp4
        # -b:a 128k  
        # if $1 is already a .mp4 or .MP4  file, add a extra suffix .mp4 to the output file
        if [[ "$1" == *.mp4 ]] || [[ "$1" == *.MP4 ]]; then
            # more agreesive compression: -crf 32  -preset fast 
            ffmpeg -i "$1" -c:v libx264 -crf 23 -preset medium -c:a aac -movflags +faststart "${1%.*}.mp4.mp4"
        else
            ffmpeg -i "$1" -c:v libx264 -crf 23 -preset medium -c:a aac -movflags +faststart "${1%.*}.mp4"
        fi
    else
        echo "$1 is not a valid file or directory"
        return
    fi
}
