#!bash

myCompressPdf() {
    # compress_pdf_aggressive.sh
    # 用法: ./compress_pdf_aggressive.sh input.pdf output.pdf
    # 极限压缩：/screen 设置 + 分块 + 并行

    INPUT="$1"
    OUTPUT="$2"
    BLOCK_SIZE=50           # 每块页数，可调
if [ `uname` = "Linux" ];
then
    CPU_CORES=$(nproc)      # Linux
else
    CPU_CORES=$(sysctl -n hw.ncpu)
fi

    tmpdir="./pdftmp"
    rm -rf "$tmpdir"
    mkdir -p "$tmpdir"
    echo "临时目录: $tmpdir"

    # 1️⃣ 分割 PDF
    echo "正在分割 PDF..."
    qpdf "$INPUT" --split-pages=1-50 "$tmpdir/part.pdf"


    xargs_extra_args="-n1"
    if [ `uname` = "Linux" ];
      echo ${xargs_extra_args}
    then
      xargs_extra_args=""
    fi


    # 2️⃣ 并行压缩每块（更小体积，低质量）
    echo "正在压缩分块 PDF（极限压缩）..."
    ls "$tmpdir"/part-*.pdf | xargs ${xargs_extra_args} -P"$CPU_CORES" -I{} gs -sDEVICE=pdfwrite \
       -dCompatibilityLevel=1.4 \
       \
       -dPDFSETTINGS=/ebook \
       \
       -dDownsampleColorImages=true \
       -dDownsampleGrayImages=true \
       -dDownsampleMonoImages=true \
       \
       -dColorImageResolution=120 \
       -dGrayImageResolution=120 \
       -dMonoImageResolution=600 \
       \
       -dAutoFilterColorImages=true \
       -dAutoFilterGrayImages=true \
       \
       -dDetectDuplicateImages=true \
       -dCompressFonts=true \
       -dSubsetFonts=true \
       -dEmbedAllFonts=true \
       \
        -dNOPAUSE -dQUIET -dBATCH -sOutputFile="{}"_compressed "{}"


    # 3️⃣ 合并压缩后的 PDF
    echo "正在合并 PDF..."
    qpdf --empty --pages "$tmpdir"/part-*.pdf_compressed -- "$OUTPUT"

    # 4️⃣ 清理临时文件
    rm -rf "$tmpdir"
    echo "完成! 输出文件: $OUTPUT"
}


function ts2date() {
    # if is Darwin
    if [ `uname` = "Darwin" ]; then
        TZ=UTC date -r $1 "+%Y-%m-%d %H:%M:%S %Z"
    else
        TZ=UTC date -d @"$1" "+%Y-%m-%d %H:%M:%S %Z"
    fi
}

function date2ts() {
    # if $1 is not provided, use current date
    if [ -z "$1" ]; then
        date +%s
    else
        # 指定输入数据 时区为 UTC
        if [ `uname` = "Darwin" ]; then
            TZ=UTC date -j -f "%Y-%m-%d %H:%M:%S" $1 "+%s"
        else
            TZ=UTC date -d "$1" "+%s"
        fi
    fi
}

function json2literal() {
    if [[ -t 0 && -f "$1" ]]; then
        # 如果有文件参数
        python3 -c 'import sys,json; print(json.dumps( json.dumps(json.load(open("'$1'")),ensure_ascii=False), ensure_ascii=False))'
    else
        # 否则从 stdin 读
        python3 -c 'import sys,json; print(json.dumps( json.dumps(json.load(sys.stdin),ensure_ascii=False), ensure_ascii=False))'
    fi
}

alias bat="bat --theme dark"
