#!bash

myCompressPdf() {
    # compress_pdf_aggressive.sh
    # 用法: ./compress_pdf_aggressive.sh input.pdf output.pdf
    # 极限压缩：/screen 设置 + 分块 + 并行

    INPUT="$1"
    OUTPUT="$2"
    BLOCK_SIZE=50           # 每块页数，可调
if [ `uname` = "Linux" ];
then
    CPU_CORES=$(nproc)      # Linux
else
    CPU_CORES=$(sysctl -n hw.ncpu)
fi

    tmpdir="./pdftmp"
    rm -rf "$tmpdir"
    mkdir -p "$tmpdir"
    echo "临时目录: $tmpdir"

    # 1️⃣ 分割 PDF
    echo "正在分割 PDF..."
    qpdf "$INPUT" --split-pages=1-50 "$tmpdir/part.pdf"


    xargs_extra_args="-n1"
    if [ `uname` = "Linux" ];
      echo ${xargs_extra_args}
    then
      xargs_extra_args=""
    fi


    # 2️⃣ 并行压缩每块（更小体积，低质量）
    echo "正在压缩分块 PDF（极限压缩）..."
    ls "$tmpdir"/part-*.pdf | xargs ${xargs_extra_args} -P"$CPU_CORES" -I{} gs -sDEVICE=pdfwrite \
       -dCompatibilityLevel=1.4 \
       \
       -dPDFSETTINGS=/ebook \
       \
       -dDownsampleColorImages=true \
       -dDownsampleGrayImages=true \
       -dDownsampleMonoImages=true \
       \
       -dColorImageResolution=120 \
       -dGrayImageResolution=120 \
       -dMonoImageResolution=600 \
       \
       -dAutoFilterColorImages=true \
       -dAutoFilterGrayImages=true \
       \
       -dDetectDuplicateImages=true \
       -dCompressFonts=true \
       -dSubsetFonts=true \
       -dEmbedAllFonts=true \
       \
        -dNOPAUSE -dQUIET -dBATCH -sOutputFile="{}"_compressed "{}"


    # 3️⃣ 合并压缩后的 PDF
    echo "正在合并 PDF..."
    qpdf --empty --pages "$tmpdir"/part-*.pdf_compressed -- "$OUTPUT"

    # 4️⃣ 清理临时文件
    rm -rf "$tmpdir"
    echo "完成! 输出文件: $OUTPUT"
}


function ts2date() {
    # if is Darwin
    if [ -z "$1" ]; then
        TZ=UTC date "+%Y-%m-%d %H:%M:%S %Z"
    else
        ts=$1
        # 如果 ts是毫秒，转换为秒
        if [ $ts -gt 1000000000000 ]; then
            ts=$(($ts / 1000))
        fi
        if [ `uname` = "Darwin" ]; then
            TZ=UTC date -r $ts "+%Y-%m-%d %H:%M:%S %Z"
        else
            TZ=UTC date -d @"ts" "+%Y-%m-%d %H:%M:%S %Z"
        fi
    fi
}

function date2ts() {
    # if $1 is not provided, use current date
    if [ -z "$1" ]; then
        date +%s
    else
        # 指定输入数据 时区为 UTC
        if [ `uname` = "Darwin" ]; then
            TZ=UTC date -j -f "%Y-%m-%d %H:%M:%S" $1 "+%s"
        else
            TZ=UTC date -d "$1" "+%s"
        fi
    fi
}

function json2literal() {
    if [[ -t 0 && -f "$1" ]]; then
        # 如果有文件参数
        python3 -c 'import sys,json; print(json.dumps( json.dumps(json.load(open("'$1'")),ensure_ascii=False), ensure_ascii=False))'
    else
        # 否则从 stdin 读
        python3 -c 'import sys,json; print(json.dumps( json.dumps(json.load(sys.stdin),ensure_ascii=False), ensure_ascii=False))'
    fi
}

myProclist () {
	procName="$1" 
	if [ -z "$procName" ]
	then
		echo "Usage: proclist procName"
		return 1
	fi
	pgrep -f $procName | xargs -I {} ps -p {} -o pid,ppid,user,group,tty,%cpu,%mem,rss,command
}

alias bat="bat --theme dark"

# login to k8s pod with fzf selection
function myl2pod() {
    # k_jd -n dev
    args=("$@")
    # it may contain alias, expand alias
    expanded_args=()
    for arg in "${args[@]}"; do
        # echo $arg
        # which whether arg is an alias, if so replace the alias name with its value
        alias_value=$(alias $arg 2>/dev/null | sed -E "s/$arg='(.*)'/\1/")
        if [ -n "$alias_value" ]; then
            expanded_args+=("$alias_value")
        else
            expanded_args+=("$arg")
        fi
    done
    # echo "Logging into pod: ${expanded_args[*]}"

    # 1 选择 pod
    pod=$(
        bash -c "${expanded_args[*]} get po --no-headers " |
        fzf |
        awk '{print $1}'
    )

    [ -z "$pod" ] && return

    # 2 获取 container 列表
    containers=($(
        bash -c "${expanded_args[*]} get po $pod -o jsonpath='{.spec.containers[*].name}'"
    ))
    # echo "Containers in pod $pod: ${containers[*]}"

    # 3. 如果有多个 container，选择一个
    if [ "${#containers[*]}" -eq 1 ]; then
        container=${containers[*]}
    else
        container=$(printf '%s\n' "${containers[@]}" | fzf)
        [ -z "$container" ] && return
    fi

    # 🔥 关键点：stdin/stdout/stderr 接回 tty
    # 管道里的 stdin 只是一根 pipe，不是终端
    # kubectl 看到的是：stdin = pipe
    # 要用当前用户真正的终端作为 stdin 
    #     /dev/tty = 当前 shell 所属的真实终端
    #     即使你在管道里，也能强行“插回去”
    # 这是处理 fzf + exec + interactive program 的通用解法。
    #
    # 4 exec 进入 pod + container
    bash -c "${expanded_args[*]} exec -it $pod -c "$container" -- /bin/bash" </dev/tty
}


# use ramdisk as tmp dir on macOS
ramDisk="/Volumes/RamDisk"
temDir="${ramDisk}/TEMPDIR"
if [ -d "$ramDisk" ] ; then
    # if tmp dir not exists, create it
    if [ ! -d "$temDir" ] ; then
        mkdir -p "$temDir"
    fi

    export TMPDIR=$temDir
    cleanTmpDir() {
        if [ -d "$temDir" ] ; then
            find "$temDir" -type f -mtime +7 -delete
        fi
    }
fi

# 用于 slog 日志输出美化
alias slog='jq -Rr '"'"'
def color_level(l):
  if l=="ERROR" then "\u001b[31m"
  elif l=="WARN" then "\u001b[35m"
  elif l=="INFO" then "\u001b[32m"
  elif l=="DEBUG" then "\u001b[33m"
  else "" end;

def color_msg(s):
  "\u001b[36m" + s + "\u001b[0m";  # cyan

(fromjson? // .) |
if type=="object" then
  "\(.time // "") " +
  (color_level(.level) + "[\(.level // "")]\u001b[0m ") +
  (color_msg(.msg // "")) +
  (del(.time,.level,.msg) | if .=={} then "" else " " + tojson end)
else
  .
end
'"'"

alias myDiskPressure="memory_pressure -l normal && vm_stat 1"


if [ `uname` = "Darwin" ]; then
    pbcopy() {
      if command -v pbcopy >/dev/null 2>&1; then
        command pbcopy
      elif command -v wl-copy >/dev/null 2>&1; then
        wl-copy
      elif command -v xclip >/dev/null 2>&1; then
        xclip -selection clipboard
      elif command -v xsel >/dev/null 2>&1; then
        xsel --clipboard --input
      else
        echo "No clipboard tool found (need wl-copy/xclip/xsel)" >&2
        return 1
      fi
    }
fi
