#!/bin/sh

# to use , vi ~/.profile, add...
# myProfile=~/".myProfile" 
# if [ -L "$myProfile" ]
# then
#     source $myProfile
# fi

# check your bash script:  https://www.shellcheck.net/

export LC_ALL=en_US.UTF-8


# ========================== PROXY =================================
ret=`lsof -i:3128`
if [ -n "$ret" ] ; then
    # proxy tunnel is running
    export _proxy=127.0.0.1:3128

    export  http_proxy=http://$_proxy
    export https_proxy=http://$_proxy
    export  HTTP_PROXY=$http_proxy
    export HTTPS_PROXY=$https_proxy

    #u3d proxy ?
    export  HTTP_proxy=$http_proxy
    export HTTPS_proxy=$https_proxy

    export NO_PROXY="localhost,127.0.0.1,10.192.*,192.168.*,kubernetes.docker.internal"
    export no_proxy=$NO_PROXY
fi

# ========================== Functions =================================

# manim shortcut
manim() {
    docker run --rm -it  --user="$(id -u):$(id -g)" -v "$(pwd)":/manim manimcommunity/manim:stable manim $@
}

# t2s 
t2sgen() {
    if [ "$#" -lt 3 ]; then
        echo 'usage: t2sgen key body.json dst_file_name'
    else
        curl -sL -X POST -H "content-type:application/json" "https://texttospeech.googleapis.com/v1beta1/text:synthesize?key=$1" -d @$2  | python3 -c "import sys,json;print(json.loads(''.join([l for l in sys.stdin]))['audioContent'])" | base64 -D  > $3.mp3
    fi
}

# use grep simulate mdfind
# case sensitive
myfindc() {
    if [ "$#" -lt 1 ]; then
        echo 'usage: myfind [opts-with-value]* "pattern" [path] [-opts-no-value]'
        echo 'grep options supported'
        echo e.g. 'myfind -m 4 -C 2 "ab test" -wh'
    else
        local  _opt="" 
        local _path="."
        local _pattern=""

        # check all parameters one by one
        while [ $# != 0 ]
        do
            # if parameter startswith `-` 
            if [[ $1 == -* ]] ; then
                if [[ $1 != *=* ]] ; then
                    # if not contains `=`, then shift and read its value
                    _opt="$_opt $1"
                    # if $# > 1, then
                    if [ $# -gt 1 ]; then
                        shift
                        # quote it
                        _opt="${_opt} "`printf "%q\n" "$1"`
                    fi
                else
                    # if contains `=`
                    # string before `=` and `=`
                    _opt="$_opt ${1%%=*}="
                    # quote string after `=`
                    _opt="${_opt}"`printf "%q\n" "${1#*=}"`
                fi
            else
                if [ -z "$_pattern" ]; then
                    _pattern=`printf "%q\n" "$1"`
                else
                    _path=`printf "%q\n" "$1"`
                fi
            fi

            shift
        done

        # echo 'opts:' "$_opt" #, 'pattern:' "$_pattern", 'path:' "$_path"
        bash -c "grep --color=always -rnI -m 1 \
            --exclude-dir=node_modules \
            --exclude-dir=.git \
            --exclude-dir=.\*_output \
            --exclude=\*.{log,} \
            --exclude=\*.min.{js,} \
            $_opt -e $_pattern $_path"
    fi
}

# case insensitive
myfind() {
    myfindc "$@" -i
}

# ========================== JAVA =================================

# if OS is darwin
if [ "$(uname)" = "Darwin" ]; then
    # Multiple JAVA versions
    export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
    export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
    export JAVA_17_HOME=$(/usr/libexec/java_home -v17)

    # can switch java version by alias easily
    alias java8='export JAVA_HOME=$JAVA_8_HOME'
    alias java11='export JAVA_HOME=$JAVA_11_HOME'
    alias java17='export JAVA_HOME=$JAVA_17_HOME'

    #default java17
    export JAVA_HOME=$JAVA_17_HOME
fi


# ========================== GO =================================
export GOROOT="$(brew --prefix go)/libexec"
export PATH=$PATH:"$HOME/go/bin"
export GO111MODULE=on

# ========================== BREW =================================
# sbin
export PATH="$PATH:/usr/local/sbin"


# ========================== MISC =================================
# pyenv
if [ "$(uname)" = "Darwin" ]; then
    export PYTHON_CONFIGURE_OPTS="--enable-framework"
if
# export PATH="$HOME/.pyenv/versions/`cat $HOME/.pyenv/version`/bin":$PATH
export PATH="$HOME/.pyenv/shims":$PATH

# PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

alias so="source ~/.profile"

# x11
if [ "$(uname)" = "Darwin" ]; then

    _display_number=`ps -ef | grep "Xquartz :\d" | grep -v xinit | awk '{ print $9; }'`
    # if _display_number is not empty, then set DISPLAY
    if [ -n "$_display_number" ]; then
         _ip=`ifconfig en0 | grep inet | awk '$1=="inet" {print $2}'` 
        xhost + $_ip  &> /dev/null
        export DISPLAY=$_ip$_display_number
        unset _ip
    else
        unset DISPLAY
    fi
    unset _display_number

fi

