set encoding=utf-8

colorscheme default

" set mouse=a

" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

" 开启语法高亮功能
syntax enable
" " 允许用指定语法高亮配色方案替换默认方案
syntax on

set number
set relativenumber


filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()


" Define bundles via Github repos
" 使用Vundle来管理Vundle
Bundle 'gmarik/vundle'

Bundle 'danro/rename.vim'
Bundle 'majutsushi/tagbar'
" systastic is used by java complete, and python syntax check
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-endwise'
" import for git status
Bundle 'tpope/vim-fugitive'
" ds cs ys 
Bundle 'tpope/vim-surround'   
Bundle 'vim-ruby/vim-ruby'
" uses exuberant ctags to build the list of tags for the current file
" Bundle 'vim-scripts/ctags.vim'
Bundle 'vim-scripts/matchit.zip'  
" jump between html tag
Bundle 'vim-scripts/tComment'
Bundle "mattn/emmet-vim"
Bundle "Lokaltog/vim-powerline"
" Bundle "jelera/vim-javascript-syntax"
Bundle "othree/html5.vim"
" automatic closing of quotes, parenthesis, brackets, etc
Bundle "Raimondi/delimitMate"

Bundle "chr4/nginx.vim"
Bundle "Lokaltog/vim-easymotion"
Bundle "ycm-core/YouCompleteMe"
" Bundle "artur-shaik/vim-javacomplete2"
Bundle "xolox/vim-misc"
Bundle "xolox/vim-lua-ftplugin"

" The tabular plugin must come before vim-markdown.
Bundle 'godlygeek/tabular'
Bundle 'plasticboy/vim-markdown'

set smartindent  
set tabstop=4  
set shiftwidth=4  
set expandtab  
set softtabstop=4  



" 定义快捷键的前缀，即<Leader>
let mapleader=";"

" 开启文件类型侦测
filetype on
" " 根据侦测到的不同类型加载对应的插件
filetype plugin on



" 总是显示状态栏
set laststatus=2
" " 显示光标当前位置
set ruler
" " 开启行号显示
set number


" " 高亮显示当前行/列
" 注意 不要开下面四句，会导致 auto complete 看不见
" set cursorline
" set cursorcolumn
" hi CursorLine   cterm=NONE ctermbg=234
" hi CursorColumn cterm=NONE ctermbg=234


" " 高亮显示搜索结果
set hlsearch

" ============== TIPS =================
" FINDING FILES:

" Serch Down into subfolders
" Provides tab-completion for all file-related tasks
" e.g: :find mat.go
set path+=**
" Display all matching files when we tab complete
" e.g: :find *.go (don't hit enter),press tab, it will popup a menu to show
" all satisfied files
set wildmenu

" TAG JUMPING
" run !ctags -R .   (bind it to you :w command ?)
" Now we can 
"   - use ^] to jump to tag under cursor
"   - g^] for ambiguous tags , it will show a list
"   - ^t  to jump back the tag stack

" AUTOCOMPLETE:
" The good stuff is documented in |ins-completion|
"   - ^x^n for JUST this file ( ^a^b means hold ctrl  )
"   - ^x^f for filenames (works with our path trick!)
"   - ^x^] for tags only
"   - ^n for anything specified by the 'complete' option

" FILE BROWSING:
" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" - :edit a folder to open a file browser
" - <CR>/v/t to open in an h-split/v-split/tab
" - check |netrw-browse-maps| for more mappings

" 查看工程文件。设置快捷键，速记：file list
nmap <Leader>fl :Lex<CR>

" SNIPPETS:
" Read an empty HTML template and move cursor to title
" nnoremap ,html :-1read $HOME/.vim/.skeleton.html<CR>3jwf>a

" en_us,de_de
" set spelllang=en_us
" set spell

" ============== PLUGINS  =================

" Go to definition else declaration
nnoremap <leader>j :YcmCompleter GoToDefinitionElseDeclaration<CR>

" don't show Maximum number of diagnostics exceeded
let g:ycm_max_diagnostics_to_display = 0
" just to new tab
let g:ycm_goto_buffer_command = 'new-or-existing-tab'
" " 主动调用补全
let g:ycm_key_invoke_completion = '<C-a>'

let g:ycm_confirm_extra_conf=0 
" tempelate has been changed, the old conf.py doesn't compatible anymore
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py'

" markdown chrome browse
autocmd BufRead,BufNewFile *.{md,mdown,mkd,mkdn,markdown,mdwn} map <Leader>md :!"/Volumes/WORK/Tools/Google Chrome.app/Contents/MacOS/Google Chrome" "%:p"<CR>

" let g:syntastic_python_flake8_args='--ignore=E,W,F401'
let g:syntastic_python_flake8_args='--ignore=W391,E501,E201,E202,E203,E221,E222,E225,E226,E231,E251,F841'
" let g:syntastic_python_flake8_args='--ignore=W291,W293,W391,E201,E202,E203,E211,E221,E222,E231,E241,E251,E261,E262,E265,E272,E301,E302,E303,E501,F405'

" syntastic java 
let g:syntastic_java_javac_config_file_enabled=1
" :SyntasticJavacEditClasspath  , run in vim
" external lib support for java completeme
" let g:JavaComplete_LibsPath=".:/usr/local/algs4/algs4.jar"

" java complete
" autocmd FileType java setlocal omnifunc=javacomplete#Complete
" Youcompleteme Java , manually disable Syntastic Java diagnostics.
let g:syntastic_java_checkers = []  
" manually disable Eclim Java diagnostics.
let g:EclimFileTypeValidate = 0

"  color 
highlight Comment ctermfg=darkgray
" colors for promt menu
" highlight Pmenu ctermfg=14 ctermbg=0 guifg=#ffffff guibg=#000000
" highlight PmenuSel ctermfg=9 ctermbg=0 guifg=#ffffff guibg=#000000

" show table
set list
set listchars=tab:>-

" lua support
let g:lua_complete_dynamic = 0 
let g:lua_complete_omni = 1

" markdown
""" disable folding
let g:vim_markdown_folding_disabled = 1
""" Set header folding level
let g:vim_markdown_folding_level = 4
let g:vim_markdown_toc_autofit = 1

" visualize text , then Ctrl-C if your vim doesn't support clipboard
" map <C-c> y:e ~/clipsongzboard<CR>P:w !pbcopy<CR><CR>:bdelete!<CR>

" debug
" let g:ycm_keep_logfiles = 1
" let g:ycm_log_level = 'debug'


