

location = /upload {
    lua_need_request_body off;
    content_by_lua_file lua/upload.lua;
}

location = /addentry {
    content_by_lua_file lua/addentry.lua;
}
location = /updateentry {
    content_by_lua_file lua/updateentry.lua;
}
location = /searchentry {
    content_by_lua_file lua/searchentry.lua;
}

