

CertainlyCode $000E _init_$14~$FF
CertainlyCode $0046 _inject_code_to_$600~$065E
CertainlyCode $346E _soundPrepare

# Hardware shit
RAM $2000 PPUCTRL
RAM $2001 PPUMASK
RAM $2002 PPUSTATUS
RAM $2003 OAMADDR
RAM $2004 OAMDATA
RAM $2005 PPUSCROLL
RAM $2006 PPUADDR
RAM $2007 PPUDATA
